## **The DATA ANALYSIS project for ICDS**

---
Test Data

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import files

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Access the file
file_path = "/content/drive/MyDrive/ICDS_DATA/test.csv"

In [ ]:
data = pd.read_csv(file_path)

In [ ]:
data

,type,area,neighborhood,description,latitude,longitude,age,floor,bedrooms,price
0,فروش ویلایی,160.0,منطقه 7 محله 17 شهریور خیابان هفده شهریور,خانه ویلایی ملکی متر فداییان اسلام (هدا...,36.263500,59.616314,0,0,3,NaN
1,فروش آپارتمان,80.0,منطقه 12 محله الهیه خیابان الهیه,متــری سجادیه /سندآماده/ واحدی/فول\r\nآپ...,36.373776,59.475820,4,1,2,NaN
2,فروش آپارتمان,82.0,منطقه 10 محله قاسم آباد خیابان قاسم آباد,متری حجاب\r\n متری سرامیک.ام دی اف .تراس. ...,36.360020,59.517400,23,1,2,NaN
3,فروش آپارتمان,75.0,منطقه 12 محله الهیه خیابان الهیه,متر الهیه برند\r\n❤️به نام خدا \n\nباعرض س...,36.373776,59.475820,7,4,2,NaN
4,فروش آپارتمان,145.0,منطقه 9 محله آب و برق خیابان اقبال لاهوری,واحدصفرنوسازکلیدنخورده فول رویایی دراقبال\r\n...,36.332903,59.469986,0,3,2,NaN
...,...,...,...,...,...,...,...,...,...,...
4605,فروش آپارتمان,68.0,منطقه 10 محله قاسم آباد خیابان قاسم آباد,متر/فول امکانات/شخصی ساز/شریعتی\r\n⭐️ مشـاو...,36.360020,59.517400,7,2,2,NaN
4606,فروش آپارتمان,170.0,منطقه 12 محله الهیه خیابان الهیه,متر صفر حاشیه بلوار الهیه\r\n⚜️ به نام خا...,36.373776,59.475820,0,1,3,NaN
4607,فروش آپارتمان,130.0,منطقه 9 محله آب و برق خیابان صیاد شیرازی,متر سه خواب/صفر/پشت حاشیه وکیل آباد\r\nمج...,36.332341,59.485542,1,5,3,NaN
4608,فروش آپارتمان,150.0,منطقه 11 محله آزاد شهر خیابان آزادشهر,سه خوابه امامت ، شمالی مستر ، باربکیو\r\n☘️با...,36.337646,59.537777,6,2,3,NaN
4609,فروش آپارتمان,100.0,منطقه 7 محله سیدی خیابان کوشش,ویلایی متری تمیز\r\nمنزل ویلایی متر داخل ...,36.265280,59.609260,5,0,2,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4610 entries, 0 to 4609
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          4610 non-null   object
 1   area          4610 non-null   float64
 2   neighborhood  4610 non-null   object
 3   description   4377 non-null   object
 4   latitude      4610 non-null   float64
 5   longitude     4610 non-null   float64
 6   age           4610 non-null   int64
 7   floor         4610 non-null   int64
 8   bedrooms      4610 non-null   int64
 9   price         0 non-null      float64
dtypes: float64(4), int64(3), object(3)
memory usage: 360.3+ KB

In [ ]:
data["type"].unique()

array(['فروش ویلایی', 'فروش آپارتمان'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

data['type'] = label_encoder.fit_transform(data['type'])
data

,type,area,neighborhood,description,latitude,longitude,age,floor,bedrooms,price
0,1,160.0,منطقه 7 محله 17 شهریور خیابان هفده شهریور,خانه ویلایی ملکی متر فداییان اسلام (هدا...,36.263500,59.616314,0,0,3,NaN
1,0,80.0,منطقه 12 محله الهیه خیابان الهیه,متــری سجادیه /سندآماده/ واحدی/فول\r\nآپ...,36.373776,59.475820,4,1,2,NaN
2,0,82.0,منطقه 10 محله قاسم آباد خیابان قاسم آباد,متری حجاب\r\n متری سرامیک.ام دی اف .تراس. ...,36.360020,59.517400,23,1,2,NaN
3,0,75.0,منطقه 12 محله الهیه خیابان الهیه,متر الهیه برند\r\n❤️به نام خدا \n\nباعرض س...,36.373776,59.475820,7,4,2,NaN
4,0,145.0,منطقه 9 محله آب و برق خیابان اقبال لاهوری,واحدصفرنوسازکلیدنخورده فول رویایی دراقبال\r\n...,36.332903,59.469986,0,3,2,NaN
...,...,...,...,...,...,...,...,...,...,...
4605,0,68.0,منطقه 10 محله قاسم آباد خیابان قاسم آباد,متر/فول امکانات/شخصی ساز/شریعتی\r\n⭐️ مشـاو...,36.360020,59.517400,7,2,2,NaN
4606,0,170.0,منطقه 12 محله الهیه خیابان الهیه,متر صفر حاشیه بلوار الهیه\r\n⚜️ به نام خا...,36.373776,59.475820,0,1,3,NaN
4607,0,130.0,منطقه 9 محله آب و برق خیابان صیاد شیرازی,متر سه خواب/صفر/پشت حاشیه وکیل آباد\r\nمج...,36.332341,59.485542,1,5,3,NaN
4608,0,150.0,منطقه 11 محله آزاد شهر خیابان آزادشهر,سه خوابه امامت ، شمالی مستر ، باربکیو\r\n☘️با...,36.337646,59.537777,6,2,3,NaN
4609,0,100.0,منطقه 7 محله سیدی خیابان کوشش,ویلایی متری تمیز\r\nمنزل ویلایی متر داخل ...,36.265280,59.609260,5,0,2,NaN

In [ ]:
data["neighborhood"].unique()

array(['منطقه 7 محله 17 شهریور  خیابان هفده شهریور',
       'منطقه 12 محله الهیه  خیابان الهیه',
       'منطقه 10 محله قاسم آباد  خیابان قاسم آباد',
       'منطقه 9 محله آب و برق   خیابان اقبال لاهوری',
       'منطقه 1 محله بعثت  خیابان رضا',
       'منطقه 12 محله الهیه  خیابان سجادیه',
       'منطقه 2 محله فرامرز عباسی  خیابان فرامرز عباسی',
       'منطقه 9 محله هنرستان  خیابان هنرستان',
       'منطقه 2 محله هدایت  خیابان عبدالمطلب',
       'منطقه 8 محله چهارراه لشکر  خیابان امام رضا',
       'منطقه 9 محله هنرستان  خیابان هفت تیر',
       'منطقه 7 محله سیدی  خیابان صبا(شهید اصلانی)',
       'منطقه 7 محله سیدی  خیابان کوشش',
       'منطقه 10 محله قاسم آباد  خیابان شاهد',
       'منطقه 7 محله 17 شهریور  خیابان نواب صفوی',
       'منطقه 11 محله دانشجو  خیابان صدف',
       'منطقه 3 محله گاز  خیابان طبرسی شمالی',
       'منطقه 2 محله هدایت  خیابان مطهری شمالی',
       'منطقه 1 محله سجاد  خیابان سجاد',
       'منطقه 2 محله هدایت  خیابان ابوطالب',
       'منطقه 11 محله آزاد شهر  خیابان امامت',
       'منطقه 1 محله آبکوه  خیابان شجریان (ارشاد سابق)',
       'منطقه 9 محله رضاشهر  خیابان سرافرازان',
       'منطقه 9 محله آب و برق   خیابان برونسی',
       'منطقه 9 محله آب و برق   خیابان صیاد شیرازی',
       'منطقه 10 محله قاسم آباد  خیابان یوسفیه',
       'منطقه 6 محله مصلی  خیابان مصلی',
       'منطقه 1 محله بعثت  خیابان کوهسنگی',
       'منطقه 4 و 5 محله طلاب  خیابان مفتح',
       'منطقه 12 محله الهیه  خیابان امیریه',
       'منطقه 4 و 5 محله طلاب  خیابان وحید',
       'منطقه 11 محله آزاد شهر  خیابان فرهنگ',
       'منطقه 11 محله دانشجو  خیابان دانشجو',
       'منطقه 9 محله آب و برق   خیابان شقایق(منطقه 9)',
       'منطقه 1 محله بعثت  خیابان احمدآباد',
       'منطقه 9 محله هنرستان  خیابان هاشمیه',
       'منطقه 8 محله چهارراه لشکر  خیابان بلوار امام خمینی',
       'منطقه 11 محله آزاد شهر  خیابان آزادشهر',
       'منطقه 11 محله دانشجو  خیابان فارغ التحصیلان',
       'منطقه 2 محله کوی امیرالمومنین  خیابان خیام شمالی',
       'منطقه 9 محله رضاشهر  خیابان باهنر',
       'منطقه 2 محله شهدا  خیابان عبادی',
       'منطقه 1 محله سجاد  خیابان فلسطین',
       'منطقه 1 محله کوهسنگی  خیابان بهشتی',
       'منطقه 9 محله آب و برق   خیابان لادن',
       'منطقه 9 محله رضاشهر  خیابان پیروزی فرد (از 1تا31 و زوج2تا30)',
       'منطقه 4 و 5 محله طلاب  خیابان علیمردانی',
       'منطقه 1 محله آبکوه  خیابان کلاهدوز',
       'منطقه 2 محله هدایت  خیابان ایثارگران',
       'منطقه 1 محله سجاد  خیابان ملک اباد',
       'منطقه 3 محله گاز  خیابان فاطمیه',
       'منطقه 2 محله هدایت  خیابان موسوی قوچانی',
       'منطقه 3 محله گاز  خیابان رسالت',
       'منطقه 10 محله قاسم آباد  خیابان حجاب',
       'منطقه 2 محله هدایت  خیابان شفا',
       'منطقه 9 محله هنرستان  خیابان کوثر جنوبی',
       'منطقه 9 محله رضاشهر  خیابان دلاوران',
       'منطقه 2 محله هدایت  خیابان هنرور',
       'منطقه 2 محله هدایت  خیابان حرعاملی',
       'منطقه 1 محله آبکوه  خیابان آبکوه',
       'منطقه 2 محله کوی امیرالمومنین  خیابان کوی امیرالمومنین',
       'منطقه 1 محله احمد آباد  خیابان سناباد',
       'منطقه 2 محله فرامرز عباسی  خیابان مهدی(فرامرز)\r\n',
       'منطقه 12 محله الهیه  خیابان رحمانیه',
       'منطقه 2 محله فرامرز عباسی  خیابان جانباز',
       'منطقه 2 محله هدایت  خیابان هدایت',
       'منطقه 6 محله مصلی  خیابان محمد آباد',
       'منطقه 2 محله هدایت  خیابان کریمی',
       'منطقه 10 محله قاسم آباد  خیابان ادیب',
       'منطقه 2 محله فرامرز عباسی  خیابان یاس(جانباز)',
       'منطقه 9 محله رضاشهر  خیابان ارغوان',
       'منطقه 4 و 5 محله طلاب  خیابان ایثار',
       'منطقه 10 محله قاسم آباد  خیابان امامیه',
       'منطقه 3 محله گاز  خیابان طبرسی جنوبی',
       'منطقه 8 محله چهارراه لشکر  خیابان سعدی',
       'منطقه 10 محله قاسم آباد  خیابان مشکینی',
       'منطقه 10 محله قاسم آباد  خیابان امام دوست',
       'منطقه 3 محله گاز  خیابان گاز',
       'منطقه 4 و 5 محله طلاب  خیابان رضائیه',
       'منطقه 10 محله قاسم آباد  خیابان شریعتی',
       'منطقه 10 محله قاسم آباد  خیابان اندیشه',
       'منطقه 6 محله مصلی  خیابان کارمندان',
       'منطقه 9 محله رضاشهر  خیابان زیتون',
       'منطقه 10 محله قاسم آباد  خیابان شهید رفیعی',
       'منطقه 11 محله آزاد شهر  خیابان دانش آموز',
       'منطقه 10 محله قاسم آباد  خیابان حسابی شمالی',
       'منطقه 2 محله کوی امیرالمومنین  خیابان ولیعصر',
       'منطقه 2 محله فرامرز عباسی  خیابان ثمانه',
       'منطقه 12 محله الهیه  خیابان اقدسیه',
       'منطقه 10 محله قاسم آباد  خیابان ابرار',
       'منطقه 11 محله دانشجو  خیابان قائم مقام فراهانی',
       'منطقه 11 محله دانشجو  خیابان ستاری',
       'منطقه 1 محله کوهسنگی  خیابان رودکی',
       'منطقه 7 محله 17 شهریور  خیابان دانش',
       'منطقه 1 محله احمد آباد  خیابان راهنمایی',
       'منطقه 1 محله سجاد  خیابان بهارستان',
       'منطقه 10 محله قاسم آباد  خیابان حسابی',
       'منطقه 7 محله 17 شهریور  خیابان پروین اعتصامی',
       'منطقه 10 محله قاسم آباد  خیابان استاد یوسفی',
       'منطقه 10 محله قاسم آباد  خیابان هاشمی رفسنجانی زوج(میثاق)',
       'منطقه 2 محله هدایت  خیابان یاس(عبدلمطلب)',
       'منطقه 1 محله آبکوه  خیابان سنایی',
       'منطقه 10 محله قاسم آباد  خیابان حسابی جنوبی',
       'منطقه 10 محله قاسم آباد  خیابان فلاحی',
       'منطقه 11 محله آزاد شهر  خیابان آموزگار فرد تا 37 و زوج تا 40',
       'منطقه 11 محله دانشجو  خیابان ارمغان',
       'منطقه 9 محله هنرستان  خیابان کوثر شمالی',
       'منطقه 7 محله 17 شهریور  خیابان فدائیان اسلام',
       'منطقه 2 محله کوی امیرالمومنین  خیابان فدک',
       'منطقه 11 محله دانشجو  خیابان نمایشگاه',
       'منطقه 9 محله رضاشهر  خیابان رضاشهر',
       'منطقه 8 محله چهارراه لشکر  خیابان ملک الشعرا بهار',
       'منطقه 9 محله رضاشهر  خیابان خاقانی',
       'منطقه 2 محله فرامرز عباسی  خیابان بهاران',
       'منطقه 2 محله فرامرز عباسی  خیابان بلوار فردوسی',
       'منطقه 9 محله آب و برق   خیابان عمادخراسانی(حافظیه)',
       'منطقه 12 محله الهیه  خیابان تقویه',
       'منطقه 10 محله قاسم آباد  خیابان بهورز',
       'منطقه 2 محله شهدا  خیابان هاشمی نژاد',
       'منطقه 2 محله شهدا  خیابان شیرازی',
       'منطقه 9 محله آب و برق   خیابان صابر',
       'منطقه 2 محله کوی امیرالمومنین  خیابان بلوار شهید شکری',
       'منطقه 12 محله الهیه  خیابان مجیدیه',
       'منطقه 8 محله چهارراه لشکر  خیابان سرشور',
       'منطقه 9 محله رضاشهر  خیابان رضوی',
       'منطقه 10 محله قاسم آباد  خیابان میعاد',
       'منطقه 12 محله الهیه  خیابان جاهد شهر',
       'منطقه 7 محله 17 شهریور  خیابان عنصری',
       'منطقه 8 محله چهارراه لشکر  خیابان آخوند خراسانی',
       'منطقه 10 محله قاسم آباد  خیابان آزاده',
       'منطقه 1 محله آبکوه  خیابان مجد',
       'منطقه 11 محله آزاد شهر  خیابان سیدرضی',
       'منطقه 9 محله هنرستان  خیابان فکوری زوج(از20تا52)فرد(17تا49)',
       'منطقه 7 محله سیدی  خیابان ایمان',
       'منطقه 6 محله مصلی  خیابان صدوقی(چهنو)',
       'منطقه 1 محله آبکوه  خیابان قاضی طباطبایی',
       'منطقه 9 محله آب و برق   خیابان پیروزی فرد(از 49تا81 و زوج54تا86)',
       'منطقه 1 محله آبکوه  خیابان مطهری جنوبی',
       'منطقه 2 محله هدایت  خیابان لاله(عبدلمطلب)',
       'منطقه 9 محله آب و برق   خیابان نور',
       'منطقه 1 محله بعثت  خیابان نوفل لوشاتو',
       'منطقه 2 محله کوی امیرالمومنین  خیابان توس',
       'منطقه 11 محله آزاد شهر  خیابان جلال آل احمد ( ایرج میرزا )',
       'منطقه 12 محله الهیه  خیابان صادقیه',
       'منطقه 12 محله الهیه  خیابان مهدیه',
       'منطقه 11 محله دانشجو  خیابان شهید قانع',
       'منطقه 11 محله دانشجو  خیابان معلم(فرداز 37-زوج از 30)',
       'منطقه 9 محله رضاشهر  خیابان فکوری زوج(از54تا92)فرد(51تا87)',
       'منطقه 11 محله آزاد شهر  خیابان سروش',
       'منطقه 11 محله دانشجو  خیابان پژوهش',
       'منطقه 9 محله آب و برق   خیابان ویلا',
       'منطقه 7 محله سیدی  خیابان شهرک ابوذر',
       'منطقه 1 محله کوهسنگی  خیابان جهان آرا',
       'منطقه 2 محله شهدا  خیابان کامیاب',
       'منطقه 9 محله هنرستان  خیابان نماز زوج از 2 تا 18 فرد از 1 تا 17',
       'منطقه 1 محله احمد آباد  خیابان پاستور',
       'منطقه 9 محله رضاشهر  خیابان نیاوران',
       'منطقه 11 محله دانشجو  خیابان دندانپزشکان',
       'منطقه 9 محله آب و برق   خیابان فکوری زوج(از2تا18)فرد(1تا15)',
       'منطقه 7 محله سیدی  خیابان قائم(کوی مهدی)\r\n',
       'منطقه 1 محله کوهسنگی  خیابان نماز فرد از 27 به بعد زوج از 26 به بعد',
       'منطقه 9 محله رضاشهر  خیابان نوکاریزی',
       'منطقه 2 محله هدایت  خیابان شیشه چی',
       'منطقه 9 محله رضاشهر  خیابان شهید کاوه',
       'منطقه 11 محله آزاد شهر  خیابان آزادی زوج(از 2 تا 50)',
       'منطقه 8 محله چهارراه لشکر  خیابان ثامن الائمه',
       'منطقه 6 محله مصلی  خیابان شیرودی',
       'منطقه 11 محله دانشجو  خیابان آموزگار(فرد از 39 زوج از42)',
       'منطقه 1 محله آبکوه  خیابان توفیق',
       'منطقه 2 محله فرامرز عباسی  خیابان رسالت (فرامرز)',
       'منطقه 2 محله هدایت  خیابان بزرگراه شهید چراغچی',
       'منطقه 9 محله آب و برق   خیابان شهرستانی'], dtype=object)

In [ ]:

# Remove "خیابان" and the text that follows it
data['neighborhood'] = data['neighborhood'].str.replace(r'\s*خیابان.*$', '')

# Display the modified DataFrame
data

<ipython-input-580-640d1a6d5df6>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  data['neighborhood'] = data['neighborhood'].str.replace(r'\s*خیابان.*$', '')

,type,area,neighborhood,description,latitude,longitude,age,floor,bedrooms,price
0,1,160.0,منطقه 7 محله 17 شهریور,خانه ویلایی ملکی متر فداییان اسلام (هدا...,36.263500,59.616314,0,0,3,NaN
1,0,80.0,منطقه 12 محله الهیه,متــری سجادیه /سندآماده/ واحدی/فول\r\nآپ...,36.373776,59.475820,4,1,2,NaN
2,0,82.0,منطقه 10 محله قاسم آباد,متری حجاب\r\n متری سرامیک.ام دی اف .تراس. ...,36.360020,59.517400,23,1,2,NaN
3,0,75.0,منطقه 12 محله الهیه,متر الهیه برند\r\n❤️به نام خدا \n\nباعرض س...,36.373776,59.475820,7,4,2,NaN
4,0,145.0,منطقه 9 محله آب و برق,واحدصفرنوسازکلیدنخورده فول رویایی دراقبال\r\n...,36.332903,59.469986,0,3,2,NaN
...,...,...,...,...,...,...,...,...,...,...
4605,0,68.0,منطقه 10 محله قاسم آباد,متر/فول امکانات/شخصی ساز/شریعتی\r\n⭐️ مشـاو...,36.360020,59.517400,7,2,2,NaN
4606,0,170.0,منطقه 12 محله الهیه,متر صفر حاشیه بلوار الهیه\r\n⚜️ به نام خا...,36.373776,59.475820,0,1,3,NaN
4607,0,130.0,منطقه 9 محله آب و برق,متر سه خواب/صفر/پشت حاشیه وکیل آباد\r\nمج...,36.332341,59.485542,1,5,3,NaN
4608,0,150.0,منطقه 11 محله آزاد شهر,سه خوابه امامت ، شمالی مستر ، باربکیو\r\n☘️با...,36.337646,59.537777,6,2,3,NaN
4609,0,100.0,منطقه 7 محله سیدی,ویلایی متری تمیز\r\nمنزل ویلایی متر داخل ...,36.265280,59.609260,5,0,2,NaN

In [ ]:
data["neighborhood"].unique()

array(['منطقه 7 محله 17 شهریور', 'منطقه 12 محله الهیه',
       'منطقه 10 محله قاسم آباد', 'منطقه 9 محله آب و برق',
       'منطقه 1 محله بعثت', 'منطقه 2 محله فرامرز عباسی',
       'منطقه 9 محله هنرستان', 'منطقه 2 محله هدایت',
       'منطقه 8 محله چهارراه لشکر', 'منطقه 7 محله سیدی',
       'منطقه 11 محله دانشجو', 'منطقه 3 محله گاز', 'منطقه 1 محله سجاد',
       'منطقه 11 محله آزاد شهر', 'منطقه 1 محله آبکوه',
       'منطقه 9 محله رضاشهر', 'منطقه 6 محله مصلی',
       'منطقه 4 و 5 محله طلاب', 'منطقه 2 محله کوی امیرالمومنین',
       'منطقه 2 محله شهدا', 'منطقه 1 محله کوهسنگی',
       'منطقه 1 محله احمد آباد', 'منطقه 2 محله فرامرز عباسی\n',
       'منطقه 7 محله سیدی\n'], dtype=object)

In [ ]:
# Check for NaN values in the 'neighborhood' column
neighborhood_nan = data['neighborhood'].isna()
nan_count = neighborhood_nan.sum()
print("Number of NaN values:", nan_count)

Number of NaN values: 0

In [ ]:
# Remove "\n" from the values in the 'neighborhood' column
data['neighborhood'] = data['neighborhood'].str.replace("\n", "")

In [ ]:
# Drop rows with NaN values in the 'neighborhood' column
data = data.dropna(subset=['neighborhood'])

# Display the cleaned DataFrame
data

,type,area,neighborhood,description,latitude,longitude,age,floor,bedrooms,price
0,1,160.0,منطقه 7 محله 17 شهریور,خانه ویلایی ملکی متر فداییان اسلام (هدا...,36.263500,59.616314,0,0,3,NaN
1,0,80.0,منطقه 12 محله الهیه,متــری سجادیه /سندآماده/ واحدی/فول\r\nآپ...,36.373776,59.475820,4,1,2,NaN
2,0,82.0,منطقه 10 محله قاسم آباد,متری حجاب\r\n متری سرامیک.ام دی اف .تراس. ...,36.360020,59.517400,23,1,2,NaN
3,0,75.0,منطقه 12 محله الهیه,متر الهیه برند\r\n❤️به نام خدا \n\nباعرض س...,36.373776,59.475820,7,4,2,NaN
4,0,145.0,منطقه 9 محله آب و برق,واحدصفرنوسازکلیدنخورده فول رویایی دراقبال\r\n...,36.332903,59.469986,0,3,2,NaN
...,...,...,...,...,...,...,...,...,...,...
4605,0,68.0,منطقه 10 محله قاسم آباد,متر/فول امکانات/شخصی ساز/شریعتی\r\n⭐️ مشـاو...,36.360020,59.517400,7,2,2,NaN
4606,0,170.0,منطقه 12 محله الهیه,متر صفر حاشیه بلوار الهیه\r\n⚜️ به نام خا...,36.373776,59.475820,0,1,3,NaN
4607,0,130.0,منطقه 9 محله آب و برق,متر سه خواب/صفر/پشت حاشیه وکیل آباد\r\nمج...,36.332341,59.485542,1,5,3,NaN
4608,0,150.0,منطقه 11 محله آزاد شهر,سه خوابه امامت ، شمالی مستر ، باربکیو\r\n☘️با...,36.337646,59.537777,6,2,3,NaN
4609,0,100.0,منطقه 7 محله سیدی,ویلایی متری تمیز\r\nمنزل ویلایی متر داخل ...,36.265280,59.609260,5,0,2,NaN

In [ ]:
data["neighborhood"].unique()

array(['منطقه 7 محله 17 شهریور', 'منطقه 12 محله الهیه',
       'منطقه 10 محله قاسم آباد', 'منطقه 9 محله آب و برق',
       'منطقه 1 محله بعثت', 'منطقه 2 محله فرامرز عباسی',
       'منطقه 9 محله هنرستان', 'منطقه 2 محله هدایت',
       'منطقه 8 محله چهارراه لشکر', 'منطقه 7 محله سیدی',
       'منطقه 11 محله دانشجو', 'منطقه 3 محله گاز', 'منطقه 1 محله سجاد',
       'منطقه 11 محله آزاد شهر', 'منطقه 1 محله آبکوه',
       'منطقه 9 محله رضاشهر', 'منطقه 6 محله مصلی',
       'منطقه 4 و 5 محله طلاب', 'منطقه 2 محله کوی امیرالمومنین',
       'منطقه 2 محله شهدا', 'منطقه 1 محله کوهسنگی',
       'منطقه 1 محله احمد آباد'], dtype=object)

In [ ]:

# Extract encoded_districts and encoded_neighborhoods
data['encoded_districts'] = data['neighborhood'].str.extract(r'(.*?) محله')
data['encoded_neighborhoods'] = data['neighborhood'].str.extract(r'محله (.*)')

# Display the modified DataFrame
data

,type,area,neighborhood,description,latitude,longitude,age,floor,bedrooms,price,encoded_districts,encoded_neighborhoods
0,1,160.0,منطقه 7 محله 17 شهریور,خانه ویلایی ملکی متر فداییان اسلام (هدا...,36.263500,59.616314,0,0,3,NaN,منطقه 7,17 شهریور
1,0,80.0,منطقه 12 محله الهیه,متــری سجادیه /سندآماده/ واحدی/فول\r\nآپ...,36.373776,59.475820,4,1,2,NaN,منطقه 12,الهیه
2,0,82.0,منطقه 10 محله قاسم آباد,متری حجاب\r\n متری سرامیک.ام دی اف .تراس. ...,36.360020,59.517400,23,1,2,NaN,منطقه 10,قاسم آباد
3,0,75.0,منطقه 12 محله الهیه,متر الهیه برند\r\n❤️به نام خدا \n\nباعرض س...,36.373776,59.475820,7,4,2,NaN,منطقه 12,الهیه
4,0,145.0,منطقه 9 محله آب و برق,واحدصفرنوسازکلیدنخورده فول رویایی دراقبال\r\n...,36.332903,59.469986,0,3,2,NaN,منطقه 9,آب و برق
...,...,...,...,...,...,...,...,...,...,...,...,...
4605,0,68.0,منطقه 10 محله قاسم آباد,متر/فول امکانات/شخصی ساز/شریعتی\r\n⭐️ مشـاو...,36.360020,59.517400,7,2,2,NaN,منطقه 10,قاسم آباد
4606,0,170.0,منطقه 12 محله الهیه,متر صفر حاشیه بلوار الهیه\r\n⚜️ به نام خا...,36.373776,59.475820,0,1,3,NaN,منطقه 12,الهیه
4607,0,130.0,منطقه 9 محله آب و برق,متر سه خواب/صفر/پشت حاشیه وکیل آباد\r\nمج...,36.332341,59.485542,1,5,3,NaN,منطقه 9,آب و برق
4608,0,150.0,منطقه 11 محله آزاد شهر,سه خوابه امامت ، شمالی مستر ، باربکیو\r\n☘️با...,36.337646,59.537777,6,2,3,NaN,منطقه 11,آزاد شهر
4609,0,100.0,منطقه 7 محله سیدی,ویلایی متری تمیز\r\nمنزل ویلایی متر داخل ...,36.265280,59.609260,5,0,2,NaN,منطقه 7,سیدی

In [ ]:
# Remove "\n" from the values in the 'neighborhood' column
data['encoded_districts'] = data['encoded_districts'].str.replace("منطقه ", "")
data

,type,area,neighborhood,description,latitude,longitude,age,floor,bedrooms,price,encoded_districts,encoded_neighborhoods
0,1,160.0,منطقه 7 محله 17 شهریور,خانه ویلایی ملکی متر فداییان اسلام (هدا...,36.263500,59.616314,0,0,3,NaN,7,17 شهریور
1,0,80.0,منطقه 12 محله الهیه,متــری سجادیه /سندآماده/ واحدی/فول\r\nآپ...,36.373776,59.475820,4,1,2,NaN,12,الهیه
2,0,82.0,منطقه 10 محله قاسم آباد,متری حجاب\r\n متری سرامیک.ام دی اف .تراس. ...,36.360020,59.517400,23,1,2,NaN,10,قاسم آباد
3,0,75.0,منطقه 12 محله الهیه,متر الهیه برند\r\n❤️به نام خدا \n\nباعرض س...,36.373776,59.475820,7,4,2,NaN,12,الهیه
4,0,145.0,منطقه 9 محله آب و برق,واحدصفرنوسازکلیدنخورده فول رویایی دراقبال\r\n...,36.332903,59.469986,0,3,2,NaN,9,آب و برق
...,...,...,...,...,...,...,...,...,...,...,...,...
4605,0,68.0,منطقه 10 محله قاسم آباد,متر/فول امکانات/شخصی ساز/شریعتی\r\n⭐️ مشـاو...,36.360020,59.517400,7,2,2,NaN,10,قاسم آباد
4606,0,170.0,منطقه 12 محله الهیه,متر صفر حاشیه بلوار الهیه\r\n⚜️ به نام خا...,36.373776,59.475820,0,1,3,NaN,12,الهیه
4607,0,130.0,منطقه 9 محله آب و برق,متر سه خواب/صفر/پشت حاشیه وکیل آباد\r\nمج...,36.332341,59.485542,1,5,3,NaN,9,آب و برق
4608,0,150.0,منطقه 11 محله آزاد شهر,سه خوابه امامت ، شمالی مستر ، باربکیو\r\n☘️با...,36.337646,59.537777,6,2,3,NaN,11,آزاد شهر
4609,0,100.0,منطقه 7 محله سیدی,ویلایی متری تمیز\r\nمنزل ویلایی متر داخل ...,36.265280,59.609260,5,0,2,NaN,7,سیدی

In [ ]:
data ["encoded_neighborhoods"].unique()

array(['17 شهریور', 'الهیه', 'قاسم آباد', 'آب و برق', 'بعثت',
       'فرامرز عباسی', 'هنرستان', 'هدایت', 'چهارراه لشکر', 'سیدی',
       'دانشجو', 'گاز', 'سجاد', 'آزاد شهر', 'آبکوه', 'رضاشهر', 'مصلی',
       'طلاب', 'کوی امیرالمومنین', 'شهدا', 'کوهسنگی', 'احمد آباد'],
      dtype=object)

In [ ]:
# Define an ordinal mapping
neighborhood_mapping = {
    'الهیه': 1,
    'فرامرز عباسی': 2,
    'هنرستان': 3 ,
    'بعثت': 4,
    'قاسم آباد': 5,
    'سجاد': 6,
    'آب و برق': 7,
    'دانشجو': 8,
    'رضاشهر':9,
    'سیدی':10,
    'چهارراه لشکر': 11,
    'هدایت': 12,
    'کوی امیرالمومنین': 13,
     'مصلی': 14,
     'آزاد شهر': 15,
     'گاز': 16,
     'کوهسنگی': 17,
     'طلاب': 18,
      'شهدا': 19,
     '17 شهریور': 20,
     'آبکوه': 21,
     'احمد آباد': 22
}


# Apply the ordinal mapping
data['encoded_neighborhoods'] = data['encoded_neighborhoods'].map(neighborhood_mapping)
data

,type,area,neighborhood,description,latitude,longitude,age,floor,bedrooms,price,encoded_districts,encoded_neighborhoods
0,1,160.0,منطقه 7 محله 17 شهریور,خانه ویلایی ملکی متر فداییان اسلام (هدا...,36.263500,59.616314,0,0,3,NaN,7,20
1,0,80.0,منطقه 12 محله الهیه,متــری سجادیه /سندآماده/ واحدی/فول\r\nآپ...,36.373776,59.475820,4,1,2,NaN,12,1
2,0,82.0,منطقه 10 محله قاسم آباد,متری حجاب\r\n متری سرامیک.ام دی اف .تراس. ...,36.360020,59.517400,23,1,2,NaN,10,5
3,0,75.0,منطقه 12 محله الهیه,متر الهیه برند\r\n❤️به نام خدا \n\nباعرض س...,36.373776,59.475820,7,4,2,NaN,12,1
4,0,145.0,منطقه 9 محله آب و برق,واحدصفرنوسازکلیدنخورده فول رویایی دراقبال\r\n...,36.332903,59.469986,0,3,2,NaN,9,7
...,...,...,...,...,...,...,...,...,...,...,...,...
4605,0,68.0,منطقه 10 محله قاسم آباد,متر/فول امکانات/شخصی ساز/شریعتی\r\n⭐️ مشـاو...,36.360020,59.517400,7,2,2,NaN,10,5
4606,0,170.0,منطقه 12 محله الهیه,متر صفر حاشیه بلوار الهیه\r\n⚜️ به نام خا...,36.373776,59.475820,0,1,3,NaN,12,1
4607,0,130.0,منطقه 9 محله آب و برق,متر سه خواب/صفر/پشت حاشیه وکیل آباد\r\nمج...,36.332341,59.485542,1,5,3,NaN,9,7
4608,0,150.0,منطقه 11 محله آزاد شهر,سه خوابه امامت ، شمالی مستر ، باربکیو\r\n☘️با...,36.337646,59.537777,6,2,3,NaN,11,15
4609,0,100.0,منطقه 7 محله سیدی,ویلایی متری تمیز\r\nمنزل ویلایی متر داخل ...,36.265280,59.609260,5,0,2,NaN,7,10

In [ ]:
data ["encoded_neighborhoods"].unique()

array([20,  1,  5,  7,  4,  2,  3, 12, 11, 10,  8, 16,  6, 15, 21,  9, 14,
       18, 13, 19, 17, 22])

In [ ]:
import pandas as pd
import random


# Extract the 'description' column as a list
description_column = data['description'].tolist()

# Randomly select 30 descriptions from the column
random_descriptions = random.sample(description_column, 30)

for description in random_descriptions:
    print(description)

 اقبال/  متر/ خواب/بازسازی شده
با سلام

   متری
  خواب
  طبقه/ واحدی/طبقه
سرامیک
هایگلس
پکیج
کولر
آسانسور
انباری
پارکینگ اختصاصی
خوش نقشه
خوش نور
  ممر


مسکن ثانی-میدان هنرستان

رحیمی زادهسال ساخت      -    خواب   :                 - طبقه   - آسانسور دارد - پارکینگ دارد - انباری دارد -
 آپارتمان     متری رفیعی فول
واحد فول بازسازی شده درجه   فروش فوری
    متری
  خواب
ابتدای رفیعی
طبقه
  واحدی
پارکینگ + انباریسال ساخت      -    خواب   :                 - طبقه   از   - آسانسور ندارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - سند : تک‌برگ -
 ویلایی    متری/عرض  /وکیل‌آباد  /گونه
درود بر شما دوستان گرامی؛

ویلایی    متری
تراکم متوسط گونه
جنوبی با عرض    متر

✓ دارای    متر زیربنا در سه واحد

☆☆گزینه‌ای عالی برای ساخت و ساز☆☆

✓ فروش ویژه بصورت نقد و یا
- تهاتر با ویلایی در اوایل وکیل‌آباد تا   میلیارد


«رحیمی هستم، مشاورِ ملکی در امور ویلایی و مشارکت»

آرشیو بیش از     فایل ویلایی کارشناسی شده و به قیمت و نیز ده‌ها مورد جهت مشارکت ..!

تماس بگیرید(   )سال ساخت      - +   خواب   :                  - پارکینگ دارد - انباری دارد - بالکن دارد - سند : تک‌برگ - جهت ساختمان : جنوبی - وضعیت واحد : بازسازی شده -
    متر صیاد شیرازی   /تاپ لوکیشن
با سلام و عرض ادب

✴️بهترین موقعیت منطقه حاشیه صیاد

〽️ سال ساخت /جنوبی

✴️ واحد/طبقه اول

〽️آسانسور کدینگ تاچ ایتالیا

✴️پارکینگ اختصاصی/تراس کاربردی و انباری
✴️ورودی لابی سنگ مدرن

〽️بدون پرت و تماما نور

✴️جهت توضیحات و بازدید لطفا فقط تماس

〽️تخلیه کلید دفتر

✴️معتمد شما:کسری لاری
               ✴️سال ساخت      -    خواب   :                 - طبقه   - آسانسور دارد - پارکینگ دارد - انباری دارد -
 آپارتمان   متری نزدیک حرم اکبری
⚜⚜⚜⚜⚜ کارشناسان مسکن اکبری ⚜ ⚜⚜⚜⚜
آدرس دفتر:مشهد،خیابان امام رضا ،حدفاصل امام رضا  و
کارشناس شما: مهندس حسینی
______________________________________
املاک اکبری بزرگترین املاک منطقه دارای  سال سابقه با بیشترین معاملات ملکی
فایل مناسب جهت سرمایه گذاران و ساکنین محترم
❗❗سند آماده انتقال❗❗
 سن بنا: صفر
 نما: سنگ کلاسیک
 کفپوش: سرامیک
 سرویس آشپزخانه: چوب
 جهت: جنوبی
سردونبش
 زیربنا:   متر
 شماره طبقه:
 تعداد طبقات:
 تعداد اتاق:
 آسانسور: دارد
 پارکینگ: دارد
 تراس: دارد
 انباری: دارد
لوکیشن بسیار عالی فاصله تاحرم  دقیقه
_____________________________________________________
جهت اطلاعات بیشتر ازین فایل یا فایل های منطقه و یا راهنمایی در خصوص خرید و فروش ملک تماس در خدمت شما عزیزان هستم.
_____________________
سپاس از همراهی شما
در پناه حقسال ساخت      -    خواب   :                 - طبقه   از   - آسانسور دارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - سند : تک‌برگ - جهت ساختمان : جنوبی -
 آپارتمان    متری دوخوابه طبقه اول با پارکینگ
سرافرازان.          آرمان.        سرافرازان
آپارتمان   متری
دوخوابه
طبقه اول با.     پارکینگ
سندشش دانگ
فوری فوری
املاک سهند        تک     نبش آرمان   آسانسور ندارد - پارکینگ دارد - انباری ندارد - تعداد واحد در طبقه   - سند : تک‌برگ - جهت ساختمان : شمالی - سال ساخت      -    خواب   :                 - طبقه   از   -
 اوایل هاشمیه آپارتمان     متری تک واحدی
لوکیشن عالی منطقه
خیابان  ٠ متری
تک واحدی
طراحی مدرن
متریال بی نظیر
کف سنگ اسلب
کابینت تمام چوب
سیستم گرمایش سرمایش چیلر
سیستم هوشمند BMS
لابی
روف گاردن   فصل
و...
 تحویل    ماه آیندهسال ساخت      -    خواب   :                  - طبقه   - آسانسور دارد - پارکینگ دارد - انباری دارد -
 پارکینگ اختصاصی
 (( ویلایی در  واحد ))             چهارراه مخابرات
⭐️   مـتـر مساحت زمین

⭐️مـوقعیت گل مخابرات

⭐️   متر بنا در  واحد

⭐️  شـمـالـی سـاز

_______________________________________________
          ⚜️⚜️⚜️ مسکن شهرآرا ⚜️⚜️⚜️پارکینگ دارد - انباری دارد - بالکن دارد - سند : تک‌برگ - جهت ساختمان : شمالی - وضعیت واحد : بازسازی شده - سال ساخت      - +   خواب   :                  -
 آپارتمان    متری/ دو خواب
««««««««کارگزاری املاک تیوان »»»»»»»»
 با احترام
آپارتمان     متری دو خواب
ابتدای سرافرازان ،سرافرازان
نوساز و شیک
تک واحدی
طبقه چهارم
کلا پنج واحد
کاغذ دیواری
کابینت ها گلس
تراس بزرگ
کمد دیواری بزرگ
کف سرامیک
سرمایش کولر گازی
گرمایش پکیج
انباری بالای پشت بام

موارد مشابه نیز موجود است

جهت اطلاعات بیشتر لطفاً تماس بگیرید
چت دیوار هم پاسخ گو هستم
املاک تیوان نبش رضوی

مشاور همراه شما
سجاد حیدریسال ساخت      -    خواب   :                 - طبقه   - آسانسور دارد - پارکینگ دارد - انباری دارد -
 آپارتمان     متری/ صفر/ تهاتر با تجاری
با سلام

✅مشاور و کارشناس تخصصی فروش: خانم فرخی

✴️آپارتمان     متری/ صفر/ دو واحدی
✴️ساختمان کلا دوازده واحد
✴️رو به نما
✴️ کلوزت/ مستر
✴️کابینت چوب/ شیر آلات گلد
✴️پات فیلر
✴️نصبیجات کامل ( لوستر/ توالت فرنگی و ...)
✴️مشاعات و کریدور تمام سنگ

❇️فروش نقدی یا تهاتر با تجاری در حاشیه
❇️در صورت تهاتر الباقی نقد پرداخت میگردد

جهت کسب اطلاعات بیشتر تماس بگیرید...

✅ کارگزاری املاک ماتیا ✅سال ساخت      -    خواب   :                 - طبقه   از   - آسانسور دارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - سند : تک‌برگ - جهت ساختمان : شمالی -
    متری تاپ لوکیشن
سلام درود

واحد    متری
لوکیشن ملک فوق العاده قوی داخل {فلاحی و حسابی شمالی }
سازنده ملک معتبر با برندی معتبر
ویو عالی خونه غرق در نور
 طبقه  از   /کلا    واحد

<<به امید خونه دار شدن تمامی همشهری ها و مردم عزیز ایران>>
بنده دهقانی مشاور خرید +فروش = (واحد های نقلی و ریز)
بین فلاحی   /   املاک پرهامسال ساخت      -    خواب   :                 - طبقه   از   - آسانسور دارد - پارکینگ دارد - انباری دارد - سند : تک‌برگ -
 آپارتمان   متری/دونبش/غرق نور/فروش
آپارتمان   متری(دونبش)

موقعیت مکانی عالی

واحد غرق نور خورشید

دسترسی به تمام امکانات در اسرع وقت

پذیرایی بسیار خوش نقشه و بدون پرتی

کابینت های گلس سفید (پرکابینت)

پارکینگ....

پر کمد دیواری.... تراس.... تراس بزرگ و به سمت کوچه

طبقه دوم (پله ها بسیار نرم و راحت)

انباری....

فایل های مشابه موجود است

کارشناس و مشاور فروش شما ذوالفقاری

املاک سراسری اشرافسال ساخت      -    خواب   :                 - طبقه   از   - آسانسور ندارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - سند : تک‌برگ - جهت ساختمان : جنوبی - وضعیت واحد : بازسازی شده -
    متر/سند آماده/معاوظه با واحد حیاط دار
با سلام
✅واحد آپارتمان     متری،دو‌ خواب
واقع در بهترین لوکیشن الهیه
نزدیک به حاشیه بلوار الهیه

✅برند نام آشنا منطقه،بسیار لوکس و مدرن

✅نمای بسیار زیبا و نورپردازی خاص
ملک دو کله و ودو ممر

✅حیاط  محوطه سازی شده ،پارکینگ تا سقف سنگ و طراحی مدرن

✅مشاعات تا سقف سنگ و نورپردازی

✅دارای آسانسور  نفره گلد هوشمند


✅کابینت هایگلس ترک/دیوار ها طراحی گچبری و کاغذ دیواری/تی وی وال/اکسنت وال/سرامیک    کالیبره/پنجره های قدی ترمال بریک/سرویس های بهداشتی سنگ اسلب/روشویی های سرویس ها سنگ/شیرآلات گلد



معاوظه با واحد حیاط دار در محدوده الهیه و مابقی نقد پرداخت میگردد.

مشاور:مختاری
املاک مدرن هدیشسال ساخت      -    خواب   :                 - طبقه   از   - آسانسور دارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - سند : تک‌برگ - جهت ساختمان : جنوبی -
     متری سه خوابه حاشیه
⬇️⬇️⬇️ بهترین لوکیشن   ⬇️⬇️⬇️
▬▬▬▬▬▬
⚜️    متر ⚜️
⚜️ دو واحدی ⚜️
⚜️ نما بسیار قوی و سنگ درجه   پر ابزار ⚜️
⚜️ محیط آرام و مسکونی ⚜️
⚜️ سه خواب نورگیر ⚜️
⚜️ سر جلو  غرق نور ⚜️
⚜️ پنجره های ترمال بریک ⚜️
⚜️ ارتفاع مفید سقف   متر ⚜️
⚜️  خواب مستر ⚜️
⚜️ آسانسور گلد ⚜️
⚜️ پارکینگ بدون مزاحمت ⚜️
⚜️ پلان معماری مهندسی بدون هدررفت متراژ⚜️
⚜️ معماری منحصر به فرد و مدرن ⚜️⚜️⚜️⚜️⚜️⚜️⚜️⚜️⚜️⚜️
          (ملک به صورت قولنامه وکالت)*
✅ قیمت بسیار مناسب
✅ فروشنده واقعی

   مشاور :داودی )

برای اطلاعات بیشتر با شماره زیر تماس بگیرید

☎️☎️☎️☎️☎️☎️☎️☎️
تلفن تماس :***********داودی


☎️☎️☎️☎️☎️☎️☎️☎️☎️☎️☎️☎️☎️☎️☎️
▬▬▬▬▬▬سال ساخت      -    خواب   :                 - طبقه   - آسانسور دارد - پارکینگ دارد - انباری دارد -
 هنرستان گلشن     متر تکواحدی
هنرستان گلشن
   متر
تکواحدی
کابینت چوب
اسانسور
لابی
کف تکسرام
پکیج اسپلیت
طراحی کلاسیک‌
فول امکانات
بی واسطهطبقه   - آسانسور دارد - پارکینگ دارد - انباری دارد - سال ساخت      -    خواب   :                  -
 اپارتمان   متری  خواب
باسلام عرض ادب
یک واحد اپارتمان    متری
 خواب جنوبی غرق نور
سند ملکی اماده انتقال
از قوی ترین برند الهیه(یزدان)
لوکیشن عالی
واقع در الهیه
مجموعه ای    واحدی
طبقه   از   طبقه
پرده ها نو کاغذ دیواری نو
کف سرامیک دارای  عدد کولر گازی
یک خواب مستر
مشاعات تمام سنگ شیک وتمیز
لابی هتلی دارای نگهبانی    ساعته
فروشنده واقعی و کاملآ منعطف
موارد مشابه موجود میباشد
مشاورامین شما:علی صادقی
دفتر مهندسی فروش املاک مینیاتور
ادرس دفتر : محمدیه  سال ساخت      -    خواب   :                 - طبقه   از   - آسانسور دارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - سند : تک‌برگ - جهت ساختمان : جنوبی -
 آپارتمان   متری  خواب/معلم/ستاری
  متر  خواب
طبقه
 واحدی
سرامیک
ام دی اف
نورگیر عالی
تراس
انباری
پارکینگ
تخلیه
موقعیت عالی
لطفا برای بازدید و اطلاعات بیشتر تماس بگیریدسال ساخت      -    خواب   :                 - طبقه   - آسانسور ندارد - پارکینگ دارد - انباری دارد -
    متر / تکواحدی  /  دیپلمات نشین
به نام خدا

✅ متراژ مفید واحد     متر تکواحدی

⚜️ مواضع سمت الهیه وقاسم اباد هم داریم

✅ گل طبقات طبقه   از پنج طبقه

✅ داری سیستم تمام هوشمند

✅  ملک جنوبی غرق درنور

✅ تمام سنگ عباس اباد

✅ محوط سازی پارکینک وپشت بام

✅ اسانسور تا پشت بام

✅ موقعیت مکانی عالی

 ✅ بهترین متریال روز

✅ اثری از سازندی بنام منطقه

✅ قابلیت دادن رهن تا    میلیون

⭐ درضمن مواضع باواحد کوچیک تر سمت الهیه وقاسم اباد

✅ بازدید مساوی باخرید


✅باتشکر مشاور شما :

                              رضا اسماعیلیسال ساخت      -    خواب   :                 - طبقه   از   - آسانسور دارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - جهت ساختمان : جنوبی - وضعیت واحد : بازسازی شده -
 دانش آموز    متر/فول  غرق نور
️یا وهاب️

عرض ادب و احترام

✅ابوالفضل حسینی هستم

با کامل ترین فایلینگ منطقه   پلاک به پلاک✅

(املاک آبان)

برای دریافت کاتالوگ عکسهای واحد پیام بگذارید
~

دانش آموز_قبل فرهنگ
   متر
شمالی
طبقه
  سال ساخت
فول بازسازی
آسانسور
پارکینگ
انباری

~

⚜درصورت عدم پاسخگویی پیام بگذارید در اولین فرصت با شما تماس میگیرم⚜

⚜صادقانه تا پایان خریدی عالی همراهتان هستیم⚜

⚜با سرچ نام مشاور خود  ابوالفضل حسینی  در دیوار به تمامی آگهی های خوش قیمت منطقه دسترسی پیدا خواهید کرد⚜

••••••••••••••••••••••

(املاک آبان)
▪︎حاشیه استقلال
بین استقلال   و   جنب محضر    ▪︎

✅مشاور همراه شما ابوالفضل حسینی✅

برای ارتباط مستقیم با مشاور خود تماس بگیرید
 سال ساخت      -    خواب   :                 - طبقه   از   - آسانسور دارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - سند : تک‌برگ - جهت ساختمان : شمالی - وضعیت واحد : بازسازی شده -
 آپارتمان     متری/ دو واحدی/ رحمانیه/ وام دار
با سلام

✅مشاور و کارشناس تخصصی فروش: خانم فرخی


✴️آپارتمان     متری/ دو واحدی/ صفر
✴️    میلیون وام از مبلغ کل کسر می‌شود
✴️رحمانیه/ واحد رو به نما
✴️نمای مدرن و اروپایی
✴️مشاعات و کریدور تمام سنگ عباس آباد
✴️ آسانسور   نفره تمام اتومات تا بام
✴️روف گاردن بی‌نظیر در منطقه

❇️ شاخصه های مهم:
✓کابینت نئو کلاسیک تا بام
✓دو خواب نورگیر مستقیم و دارای کمد
✓مستر
✓روشنایی هوشمند (Bms)
✓سیستم صوتی
✓نصبیجات کامل

جهت کسب اطلاعات بیشتر تماس بگیرید...

✅ کارگزاری املاک ماتیا ✅طبقه   از   - آسانسور دارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - سند : تک‌برگ - جهت ساختمان : شمالی - سال ساخت      -    خواب   :                 -
nan
 ویلایی     متری ابکو
    متر زمین دونبش

    متر بنا در  طبقه

موقعیت ملک عالی

            هادیسال ساخت      - +   خواب   :                  - پارکینگ دارد - انباری دارد - بالکن دارد -
 یک واحد آپارتمان     متری صفر فول امکانات شیک
یک واحد آپارتمان     متری صفر فول امکانات شیک طبقه اول در محدوده بهشتی خیابان پهن .
املاک عطار
همکار گرامی تماس نگیرید
با سرچ اسم ( حامد عطار )  تمامی موارد املاک عطار برای شما قابل مشاهده میباشد .سال ساخت      -    خواب   :                 - طبقه   از   - آسانسور دارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - سند : تک‌برگ - جهت ساختمان : شمالی -
 راه جدا
 اپارتمان     متری دوکله
ملک واقع در شهرک پردیس،موقعیت مکانی عالی،دو کله
سازنده معتبر منطقه
امکانات فول
سرامیک
کابینت چوب
مطبخ
اتاق مستر
پول لازمم،چون دارم ملک دیگه ای میخرم
زیر قیمت حاضر به معامله هستمسال ساخت      -    خواب   :                 - طبقه   از   - آسانسور دارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - سند : سایر - جهت ساختمان : جنوبی -
    متر/صفر/بدون مشرف/الهیه
⚜️ کارگزاری مسکن رویال ⚜️ الهیه
    بزرگترین و جامع ترین فایلینگ منطقه
➖️➖️➖️➖️➖️➖️➖️️➖️➖️➖️➖️➖️➖️➖️➖️
️پلان تفکیک شده و بدون فضای پرت
طراحی مدرن با متریال درجه
️سازه با بهره بری از به روزترین سیستم باربری جانبی [ سیستم مقابله با زلزله و باد و طوفان ]
️ورودی و لابی مجلل
️بهره گیری از بالاترین سطح کیفیت در متریال مطابق استاندارد های به روز
️عایق صوتی و حرارتی دیوارها
️ روف گاردن
️کاملا شناور در نور
️چشم انداز بی نظیر
️فروشنده واقعی و منعطف
✅️ مشاور و کارشناس فروش: نخعی

 دارای ️تنوع زیاد فایل ها با هر نوع سلیقه و بودجهسال ساخت      -    خواب   :                 - طبقه   از   - آسانسور دارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - سند : تک‌برگ - جهت ساختمان : شمالی - وضعیت واحد : بازسازی شده -
 آپارتمان    متر  * صفر *   خواب
《به نام ایزد منان》

➖️➖️➖️➖️➖️➖️➖️➖️➖️➖️➖️
                                ROYAL
          آژانس املاک مورد اعتماد شما
نماینده مستقیم فروش معتبر ترین برندهای الهیه
▪︎پیش فروش   ▪︎آماده تحویل   ▪︎سند آماده
➖️➖️➖️➖️➖️➖️➖️➖️➖️➖️➖️


     ⛔️ قابل توجه سرمایه گذاران محترم ⛔️

 ➖️➖️➖️➖️➖️
✅️ بسیار خوش نقشه، پلان مهندسی
      پذیرایی خوش چیدمان و پرنور.

✅️ آشپزخانه دلباز و پرنور.
      کابینت چوب قابل شستشو.

✅️  خواب نور / پنجره قدی بزرگ
      کمد دیواری جادار.
      حمام مستر.

✅️ مشاعات فضا سازی شده.
      و ...

➖️➖️➖️➖️➖️➖️➖️➖️➖️➖️➖️
موارد مشابه مناسب با سلیقه و بودجه شما موجود میباشد.
مسکن رویال، رحمانیه
کارشناس فروش: امیر میرشاهیجهت ساختمان : جنوبی - سال ساخت      -    خواب   :                 - طبقه   از   - آسانسور دارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - سند : تک‌برگ -
 اپارتمان
اپارتمان    متری .ساختمون دو کله .طبقه دوم رو پیلوت .با فنداسیون قوی .حاشیه خیابون اصلی از دو طرف نور داره . حاشیه ملک  متر در مرحله سفتکاری فروخته میشه .با سود دهی بالا .مجوز دارم هست .موقعیتش عالی حاشیه منتتظری .درودی   حاشیه   متریسال ساخت      -    خواب   :                 - طبقه   - آسانسور دارد - پارکینگ ندارد - انباری دارد -
   مترمجیدیه  /فول کامل
سلام و عرض ادب
درب ضدسرقت
کابینت آشپزخانه های گلاس
شیرآلات بهداشتی اهرمی
نقاشی وقاب بندی تیوی سط
کف پوش سرامیک
گرمایش پکیج و رادیاتور وگازروکار وهودلمسی و کولرآبی وحوله خشک کن نسب است
کمد دیواری و هردو اتاق خواب نورگیر مستقیم
قابلیت رهن کامل    میلیون
   م تعهدسند
بازدید
بلوار الهیه بین الهیه   ومیدان محمدیه املاک صمصام معینیسال ساخت      -    خواب   :                 - طبقه   از   - آسانسور دارد - پارکینگ دارد - انباری دارد - تعداد واحد در طبقه   - سند : تک‌برگ - جهت ساختمان : شمالی -

In [ ]:
data['description'].fillna("هیچی", inplace=True)

In [ ]:
# Check for NaN values in the 'neighborhood' column
neighborhood_nan = data['description'].isna()
nan_count = neighborhood_nan.sum()
print("Number of NaN values:", nan_count)

Number of NaN values: 0

In [ ]:
# Removing the stop words

# List of words to remove
words_to_remove = [
    "آسانسور ندارد",
    "بدون آسانسور",
    "پارکینگ ندارد",
    "بدون پارکینگ",
    "انباری ندارد",
    "بدون انباری"
]

# Function to remove specified words from a string
def remove_words(text):
    if isinstance(text, str):
        for word in words_to_remove:
            text = text.replace(word, "")
        return text.strip()
    else:
        return text

# Apply the remove_words function to the 'description' column
data['description'] = data['description'].apply(remove_words)

data

,type,area,neighborhood,description,latitude,longitude,age,floor,bedrooms,price,encoded_districts,encoded_neighborhoods
0,1,160.0,منطقه 7 محله 17 شهریور,خانه ویلایی ملکی متر فداییان اسلام (هدای...,36.263500,59.616314,0,0,3,NaN,7,20
1,0,80.0,منطقه 12 محله الهیه,متــری سجادیه /سندآماده/ واحدی/فول\r\nآپارت...,36.373776,59.475820,4,1,2,NaN,12,1
2,0,82.0,منطقه 10 محله قاسم آباد,متری حجاب\r\n متری سرامیک.ام دی اف .تراس. پار...,36.360020,59.517400,23,1,2,NaN,10,5
3,0,75.0,منطقه 12 محله الهیه,متر الهیه برند\r\n❤️به نام خدا \n\nباعرض سلام ...,36.373776,59.475820,7,4,2,NaN,12,1
4,0,145.0,منطقه 9 محله آب و برق,واحدصفرنوسازکلیدنخورده فول رویایی دراقبال\r\nب...,36.332903,59.469986,0,3,2,NaN,9,7
...,...,...,...,...,...,...,...,...,...,...,...,...
4605,0,68.0,منطقه 10 محله قاسم آباد,متر/فول امکانات/شخصی ساز/شریعتی\r\n⭐️ مشـاوریـ...,36.360020,59.517400,7,2,2,NaN,10,5
4606,0,170.0,منطقه 12 محله الهیه,متر صفر حاشیه بلوار الهیه\r\n⚜️ به نام خالق یک...,36.373776,59.475820,0,1,3,NaN,12,1
4607,0,130.0,منطقه 9 محله آب و برق,متر سه خواب/صفر/پشت حاشیه وکیل آباد\r\nمجموعه ...,36.332341,59.485542,1,5,3,NaN,9,7
4608,0,150.0,منطقه 11 محله آزاد شهر,سه خوابه امامت ، شمالی مستر ، باربکیو\r\n☘️با ...,36.337646,59.537777,6,2,3,NaN,11,15
4609,0,100.0,منطقه 7 محله سیدی,ویلایی متری تمیز\r\nمنزل ویلایی متر داخل د...,36.265280,59.609260,5,0,2,NaN,7,10

In [ ]:

# List of words and their corresponding scores
keywords_and_scores = {
    "پارکینگ": 1,
    "انباری": 1,
    "آسانسور": 1,
    "کولر گازی": 1,
    "کولرگازی": 1,
    "دونبش": 1,
    "دو نبش": 1,
    "وان": 1,
    "لابی": 1,
    "نورگیر": 1
}

# Function to calculate the total score for a description
def calculate_score(description):
    score = 0
    for keyword, keyword_score in keywords_and_scores.items():
        if keyword in description:
            score += keyword_score
    return score

# Apply the calculate_score function to the 'description' column and store in 'description_score' column
data['description_score'] = data['description'].apply(calculate_score)

data

,type,area,neighborhood,description,latitude,longitude,age,floor,bedrooms,price,encoded_districts,encoded_neighborhoods,description_score
0,1,160.0,منطقه 7 محله 17 شهریور,خانه ویلایی ملکی متر فداییان اسلام (هدای...,36.263500,59.616314,0,0,3,NaN,7,20,2
1,0,80.0,منطقه 12 محله الهیه,متــری سجادیه /سندآماده/ واحدی/فول\r\nآپارت...,36.373776,59.475820,4,1,2,NaN,12,1,5
2,0,82.0,منطقه 10 محله قاسم آباد,متری حجاب\r\n متری سرامیک.ام دی اف .تراس. پار...,36.360020,59.517400,23,1,2,NaN,10,5,2
3,0,75.0,منطقه 12 محله الهیه,متر الهیه برند\r\n❤️به نام خدا \n\nباعرض سلام ...,36.373776,59.475820,7,4,2,NaN,12,1,3
4,0,145.0,منطقه 9 محله آب و برق,واحدصفرنوسازکلیدنخورده فول رویایی دراقبال\r\nب...,36.332903,59.469986,0,3,2,NaN,9,7,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4605,0,68.0,منطقه 10 محله قاسم آباد,متر/فول امکانات/شخصی ساز/شریعتی\r\n⭐️ مشـاوریـ...,36.360020,59.517400,7,2,2,NaN,10,5,4
4606,0,170.0,منطقه 12 محله الهیه,متر صفر حاشیه بلوار الهیه\r\n⚜️ به نام خالق یک...,36.373776,59.475820,0,1,3,NaN,12,1,4
4607,0,130.0,منطقه 9 محله آب و برق,متر سه خواب/صفر/پشت حاشیه وکیل آباد\r\nمجموعه ...,36.332341,59.485542,1,5,3,NaN,9,7,4
4608,0,150.0,منطقه 11 محله آزاد شهر,سه خوابه امامت ، شمالی مستر ، باربکیو\r\n☘️با ...,36.337646,59.537777,6,2,3,NaN,11,15,4
4609,0,100.0,منطقه 7 محله سیدی,ویلایی متری تمیز\r\nمنزل ویلایی متر داخل د...,36.265280,59.609260,5,0,2,NaN,7,10,2

In [ ]:
data["description_score"].unique()

array([2, 5, 3, 4, 1, 6, 0, 7, 8])

In [ ]:
# Add another column 'full_facilities_score' and increase the score by 1 if 'فول امکانات' is present
data['full_facilities_score'] = data['description'].apply(lambda x: 1 if 'فول امکانات' in x else 0)
data

,type,area,neighborhood,description,latitude,longitude,age,floor,bedrooms,price,encoded_districts,encoded_neighborhoods,description_score,full_facilities_score
0,1,160.0,منطقه 7 محله 17 شهریور,خانه ویلایی ملکی متر فداییان اسلام (هدای...,36.263500,59.616314,0,0,3,NaN,7,20,2,0
1,0,80.0,منطقه 12 محله الهیه,متــری سجادیه /سندآماده/ واحدی/فول\r\nآپارت...,36.373776,59.475820,4,1,2,NaN,12,1,5,0
2,0,82.0,منطقه 10 محله قاسم آباد,متری حجاب\r\n متری سرامیک.ام دی اف .تراس. پار...,36.360020,59.517400,23,1,2,NaN,10,5,2,0
3,0,75.0,منطقه 12 محله الهیه,متر الهیه برند\r\n❤️به نام خدا \n\nباعرض سلام ...,36.373776,59.475820,7,4,2,NaN,12,1,3,1
4,0,145.0,منطقه 9 محله آب و برق,واحدصفرنوسازکلیدنخورده فول رویایی دراقبال\r\nب...,36.332903,59.469986,0,3,2,NaN,9,7,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4605,0,68.0,منطقه 10 محله قاسم آباد,متر/فول امکانات/شخصی ساز/شریعتی\r\n⭐️ مشـاوریـ...,36.360020,59.517400,7,2,2,NaN,10,5,4,1
4606,0,170.0,منطقه 12 محله الهیه,متر صفر حاشیه بلوار الهیه\r\n⚜️ به نام خالق یک...,36.373776,59.475820,0,1,3,NaN,12,1,4,0
4607,0,130.0,منطقه 9 محله آب و برق,متر سه خواب/صفر/پشت حاشیه وکیل آباد\r\nمجموعه ...,36.332341,59.485542,1,5,3,NaN,9,7,4,0
4608,0,150.0,منطقه 11 محله آزاد شهر,سه خوابه امامت ، شمالی مستر ، باربکیو\r\n☘️با ...,36.337646,59.537777,6,2,3,NaN,11,15,4,0
4609,0,100.0,منطقه 7 محله سیدی,ویلایی متری تمیز\r\nمنزل ویلایی متر داخل د...,36.265280,59.609260,5,0,2,NaN,7,10,2,0

In [ ]:
# Check for NaN values in the 'neighborhood' column
neighborhood_nan = data['age'].isna()
nan_count = neighborhood_nan.sum()
print("Number of NaN values:", nan_count)

Number of NaN values: 0

In [ ]:
data["age"].unique()

array([ 0,  4, 23,  7, 17, 12, 16, 22, 15,  5,  2,  1, 11, 18,  9, 20,  8,
       26,  6, 10, 14, 13, 19,  3, 25, 30, 27, 28, 31, 24, 21, 29])

In [ ]:


# # Replace the phrase "سال ساخت" with an empty string in the 'age' column
# data['age'] = data['age'].str.replace("سال ساخت", "")
# data['age'] = data['age'].str.replace(" ", "")
# data['age'] = data['age'].str.replace("تازهساز", "0")
# data['age'] = data['age'].str.replace("1402", "0")
# data['age'] = data['age'].str.replace("1387", "15")
# data['age'] = data['age'].str.replace("1401", "1")
# data

In [ ]:
data["age"].unique()

array([ 0,  4, 23,  7, 17, 12, 16, 22, 15,  5,  2,  1, 11, 18,  9, 20,  8,
       26,  6, 10, 14, 13, 19,  3, 25, 30, 27, 28, 31, 24, 21, 29])

In [ ]:
# Analyzing NAN in gage column

# Filter and display rows with NaN values in the 'age' column
nan_age_rows = data[data['age'].isna()]
nan_age_rows

Empty DataFrame
Columns: [type, area, neighborhood, description, latitude, longitude, age, floor, bedrooms, price, encoded_districts, encoded_neighborhoods, description_score, full_facilities_score]
Index: []

In [ ]:
# Find rows with specific keywords in 'description' column and set 'age' to 0
keywords = ["نوساز", "نو ساز", "صفر", "تازهساخت", "تازه", "تازه ساخت", "کلید نخورده", "کلیدنخورده", "کلید نخرده", "کلیدنخرده", "نازک کاری", "نازککاری", "سفتکاری", "سفت کاری","مرحله", "سال نو", ]

for keyword in keywords:
    mask = data['description'].str.contains(keyword)
    data.loc[mask, 'age'] = 0

In [ ]:
# Find rows with specific keywords in 'description' column and set 'age' to 0
keywords = ["تک برگ", "تکبرگ" ]

for keyword in keywords:
    mask = data['description'].str.contains(keyword)
    data.loc[mask, 'age'] = 2

In [ ]:
# Find rows with specific keywords in 'description' column and set 'age' to a random number bewteen 1 and 4
keywords = ["روف گاردن", "روفگاردن", "جکوزی", "فضاسازی", "فضا سازی", "مستر", "ترمالبریک", "ترمال بریک", "جزیره"]

for keyword in keywords:
    mask = data['description'].str.contains(keyword)
    data.loc[mask, 'age'] = random.randint(1, 4)

In [ ]:
# Find rows with specific keywords in 'description' column and set 'age' to 30
keywords = ["کلنگی", "تخریب", "آماده ساخت", "مجوز ساخت", "آمادهساخت", "مجوزساخت", "پروانه"]

for keyword in keywords:
    mask = data['description'].str.contains(keyword)
    data.loc[mask, 'age'] = 30

In [ ]:
# Find rows with specific keywords in 'description' column and set 'age' to 15
keywords = ["بازسازی"]

for keyword in keywords:
    mask = data['description'].str.contains(keyword)
    data.loc[mask, 'age'] = 15

In [ ]:
# Iwonder i can find the years of building the apartment or house
keywords = ["1402", "1401", "1400"]

total_matches = 0  # Initialize the count of matches

for keyword in keywords:
    mask = data['description'].str.contains(keyword)
    total_matches += mask.sum()

print("Total matches:", total_matches)

# Unfortunately NO MATCH

Total matches: 0

In [ ]:
# Check for NaN values in the 'neighborhood' column
age_nan = data["age"].isna()
nan_count = age_nan.sum()
print("Number of NaN values:", nan_count)

Number of NaN values: 0

In [ ]:
nan_age_rows = data[data['age'].isna()]
nan_age_rows

Empty DataFrame
Columns: [type, area, neighborhood, description, latitude, longitude, age, floor, bedrooms, price, encoded_districts, encoded_neighborhoods, description_score, full_facilities_score]
Index: []

In [ ]:
# # Extract the 'description' column as a list
# description_column = nan_age_rows['description'].tolist()

# # Randomly select 30 descriptions from the column
# random_descriptions = random.sample(description_column, 30)

# for description in random_descriptions:
#     print(description)

In [ ]:
# Generate random numbers between 1 and 30
random_numbers = np.random.randint(1, 31, size=data['age'].isnull().sum())

# Fill NaN cells in 'age' column with random numbers
data.loc[data['age'].isnull(), 'age'] = random_numbers

data

,type,area,neighborhood,description,latitude,longitude,age,floor,bedrooms,price,encoded_districts,encoded_neighborhoods,description_score,full_facilities_score
0,1,160.0,منطقه 7 محله 17 شهریور,خانه ویلایی ملکی متر فداییان اسلام (هدای...,36.263500,59.616314,15,0,3,NaN,7,20,2,0
1,0,80.0,منطقه 12 محله الهیه,متــری سجادیه /سندآماده/ واحدی/فول\r\nآپارت...,36.373776,59.475820,4,1,2,NaN,12,1,5,0
2,0,82.0,منطقه 10 محله قاسم آباد,متری حجاب\r\n متری سرامیک.ام دی اف .تراس. پار...,36.360020,59.517400,23,1,2,NaN,10,5,2,0
3,0,75.0,منطقه 12 محله الهیه,متر الهیه برند\r\n❤️به نام خدا \n\nباعرض سلام ...,36.373776,59.475820,7,4,2,NaN,12,1,3,1
4,0,145.0,منطقه 9 محله آب و برق,واحدصفرنوسازکلیدنخورده فول رویایی دراقبال\r\nب...,36.332903,59.469986,0,3,2,NaN,9,7,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4605,0,68.0,منطقه 10 محله قاسم آباد,متر/فول امکانات/شخصی ساز/شریعتی\r\n⭐️ مشـاوریـ...,36.360020,59.517400,15,2,2,NaN,10,5,4,1
4606,0,170.0,منطقه 12 محله الهیه,متر صفر حاشیه بلوار الهیه\r\n⚜️ به نام خالق یک...,36.373776,59.475820,2,1,3,NaN,12,1,4,0
4607,0,130.0,منطقه 9 محله آب و برق,متر سه خواب/صفر/پشت حاشیه وکیل آباد\r\nمجموعه ...,36.332341,59.485542,0,5,3,NaN,9,7,4,0
4608,0,150.0,منطقه 11 محله آزاد شهر,سه خوابه امامت ، شمالی مستر ، باربکیو\r\n☘️با ...,36.337646,59.537777,15,2,3,NaN,11,15,4,0
4609,0,100.0,منطقه 7 محله سیدی,ویلایی متری تمیز\r\nمنزل ویلایی متر داخل د...,36.265280,59.609260,5,0,2,NaN,7,10,2,0

In [ ]:
# Check for NaN values in the 'age' column
age_nan = data["age"].isna()
nan_count = age_nan.sum()
print("Number of NaN values:", nan_count)

Number of NaN values: 0

In [ ]:
# Check for NaN values in the 'floor' column
age_nan = data["floor"].isna()
nan_count = age_nan.sum()
print("Number of NaN values:", nan_count)

Number of NaN values: 0

In [ ]:
data["floor"].unique()

array([ 0,  1,  4,  3,  2,  5, -1,  7,  6,  9,  8, 10, 11, 12])

In [ ]:
# data['floor'] = data['floor'].str.replace("همکف", "0")
# data["floor"].unique()

In [ ]:
data["bedrooms"].unique()

array([3, 2, 4, 1, 5, 0])

In [ ]:
# Check for NaN values in the 'bedrooms' column
age_nan = data["bedrooms"].isna()
nan_count = age_nan.sum()
print("Number of NaN values:", nan_count)

Number of NaN values: 0

In [ ]:
nan_age_rows = data[data['bedrooms'].isna()]
nan_age_rows

Empty DataFrame
Columns: [type, area, neighborhood, description, latitude, longitude, age, floor, bedrooms, price, encoded_districts, encoded_neighborhoods, description_score, full_facilities_score]
Index: []

In [ ]:
# Replace NaN value in 'bedrooms' column at row 2915 with 4 and row 25622 with 1
data.loc[2915, 'bedrooms'] = 4
data.loc[25622, 'bedrooms'] = 1

In [ ]:
data["bedrooms"].unique()

array([3., 2., 4., 1., 5., 0.])

In [ ]:
# data['price'] = data['price'].str.replace("تومان", "")
# data

In [ ]:
data["price"].unique()

array([nan])

In [ ]:
data = data.drop(columns=['price'])

In [ ]:
# Check for NaN values in the 'x' column
age_nan = data["bedrooms"].isna()
nan_count = age_nan.sum()
print("Number of NaN values:", nan_count)

# type ----> CLEAN
# area ----> CLEAN
# encoded_districts ----> CLEAN
# encoded_neighborhoods ----> CLEAN
# description_score ----> CLEAN
# full_facilities_score ----> CLEAN
# latitude ----> CLEAN
# longitude ----> CLEAN
# age ----> CLEAN
# floor ----> CLEAN
# bedrooms ----> CLEAN

Number of NaN values: 0

In [ ]:
data["encoded_districts"].unique()

array(['7', '12', '10', '9', '1', '2', '8', '11', '3', '6', '4 و 5', nan],
      dtype=object)

In [ ]:
data["encoded_districts"] = data["encoded_districts"].replace("4 و 5", "45")

In [ ]:
data["encoded_districts"].unique()

array(['7', '12', '10', '9', '1', '2', '8', '11', '3', '6', '45', nan],
      dtype=object)

In [ ]:
# Drop the 'description' and 'neighborhood' columns
data.drop(['description', 'neighborhood'], axis=1, inplace=True)

In [ ]:
# Use numpy to count the number of rows with price = 0
# count_zero_prices = np.sum(data['price'] == 0)

# print(f"Number of rows with price = 0: {count_zero_prices}")

In [ ]:
# Drop the 'description' and 'neighborhood' columns
# data.drop(['price'], axis=1, inplace=True)
# data
# data["price"] = data["price"].replace("  ", "")
# data["price"] = data["price"].replace("   ", "")
# data["price"] = data["price"].replace("    ", "")
# data["price"] = data["price"].replace("     ", "")
# data["price"] = data["price"].replace("      ", "")
# data["price"] = data["price"].replace(",", "")
# data["price"].unique()

In [ ]:
data

,type,area,latitude,longitude,age,floor,bedrooms,encoded_districts,encoded_neighborhoods,description_score,full_facilities_score
0,1.0,160.0,36.263500,59.616314,15.0,0.0,3.0,7,20.0,2.0,0.0
1,0.0,80.0,36.373776,59.475820,4.0,1.0,2.0,12,1.0,5.0,0.0
2,0.0,82.0,36.360020,59.517400,23.0,1.0,2.0,10,5.0,2.0,0.0
3,0.0,75.0,36.373776,59.475820,7.0,4.0,2.0,12,1.0,3.0,1.0
4,0.0,145.0,36.332903,59.469986,0.0,3.0,2.0,9,7.0,5.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4606,0.0,170.0,36.373776,59.475820,2.0,1.0,3.0,12,1.0,4.0,0.0
4607,0.0,130.0,36.332341,59.485542,0.0,5.0,3.0,9,7.0,4.0,0.0
4608,0.0,150.0,36.337646,59.537777,15.0,2.0,3.0,11,15.0,4.0,0.0
4609,0.0,100.0,36.265280,59.609260,5.0,0.0,2.0,7,10.0,2.0,0.0
25622,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN

In [ ]:
# Convert the 'price' column to numeric
# data['price'] = pd.to_numeric(data['price'])

In [ ]:
# Convert the 'age' column to numeric
data['age'] = pd.to_numeric(data['age'])

# Convert the 'floor' column to numeric
data['floor'] = pd.to_numeric(data['floor'])

# Convert the 'encoded_districts' column to numeric
data['encoded_districts'] = pd.to_numeric(data['encoded_districts'])

In [ ]:
# # Clean up the 'price' column
# data['price'] = data['price'].str.replace(',', '').str.strip()

# # Convert the cleaned 'price' column to numeric
# data['price'] = pd.to_numeric(data['price'], errors='coerce')

# # Count the number of rows with price = 0
# count_zero_prices = np.sum(data['price'] == 0)

In [ ]:
# Convert the 'encoded_districts' column to numeric
# data['price'] = pd.to_numeric(data['price'])

In [ ]:
data["age"].unique()

# type ----> CLEAN - Numerical
# area ----> CLEAN - Numerical
# encoded_districts ----> CLEAN - Numerical
# encoded_neighborhoods ----> CLEAN - Numerical
# description_score ----> CLEAN - Numerical
# full_facilities_score ----> CLEAN - Numerical
# latitude ----> CLEAN - Numerical
# longitude ----> CLEAN - Numerical
# age ----> CLEAN - Numerical
# floor ----> CLEAN - Numerical
# bedrooms ----> CLEAN - Numerical

array([15.,  4., 23.,  7.,  0., 16., 17., 22.,  3.,  5.,  2.,  1., 11.,
       18.,  9., 12.,  8., 20.,  6., 10., 19., 14., 30., 28., 13., 21.,
       27., 31., 26., 29., 25., 24., nan])

In [ ]:
data.describe()

,type,area,latitude,longitude,age,floor,bedrooms,encoded_districts,encoded_neighborhoods,description_score,full_facilities_score
count,4610.000000,4610.000000,4610.000000,4610.000000,4610.000000,4610.000000,4611.000000,4610.000000,4610.000000,4610.000000,4610.000000
mean,0.076573,118.965206,36.330755,59.528755,8.111280,2.467679,2.294947,9.314967,7.063341,2.885900,0.117354
std,0.265941,44.055700,0.034063,0.054209,6.968857,1.701255,0.731811,7.482136,5.788068,1.422625,0.321876
min,0.000000,30.000000,36.204212,59.388190,0.000000,-1.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,0.000000,85.000000,36.310135,59.475820,2.000000,1.000000,2.000000,7.000000,2.000000,2.000000,0.000000
50%,0.000000,110.000000,36.327540,59.513390,5.000000,2.000000,2.000000,9.000000,5.000000,3.000000,0.000000
75%,0.000000,150.000000,36.366621,59.571770,15.000000,4.000000,3.000000,12.000000,11.000000,4.000000,0.000000
max,1.000000,290.000000,36.458290,59.774284,31.000000,12.000000,5.000000,45.000000,22.000000,8.000000,1.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4611 entries, 0 to 25622
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   type                   4610 non-null   float64
 1   area                   4610 non-null   float64
 2   latitude               4610 non-null   float64
 3   longitude              4610 non-null   float64
 4   age                    4610 non-null   float64
 5   floor                  4610 non-null   float64
 6   bedrooms               4611 non-null   float64
 7   encoded_districts      4610 non-null   float64
 8   encoded_neighborhoods  4610 non-null   float64
 9   description_score      4610 non-null   float64
 10  full_facilities_score  4610 non-null   float64
dtypes: float64(11)
memory usage: 561.3 KB

In [ ]:
# Write the data to a new CSV file
data.to_csv('new_test_data.csv', index=False)

In [ ]:
# Download the new CSV file
files.download('new_test_data.csv')